// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for Blog documents */
interface BlogDocumentData {
  /**
   * Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Slice Zone field in *Blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice>;
}
/**
 * Slice for *Blog → Slice Zone*
 *
 */
type BlogDocumentDataSlicesSlice = BlogQuoteSlice;
/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BlogDocumentData>, "blog", Lang>;
/** Content for Blog Category documents */
type BlogCategoryDocumentData = Record<string, never>;
/**
 * Blog Category document from Prismic
 *
 * - **API ID**: `blog_category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogCategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogCategoryDocumentData>,
    "blog_category",
    Lang
  >;
export type AllDocumentTypes = BlogDocument | BlogCategoryDocument;
/**
 * Primary content in BlogQuote → Primary
 *
 */
interface BlogQuoteSliceDefaultPrimary {
  /**
   * Quote field in *BlogQuote → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_quote.primary.quote
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  quote: prismic.RichTextField;
  /**
   * Author field in *BlogQuote → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_quote.primary.author
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  author: prismic.KeyTextField;
}
/**
 * Default variation for BlogQuote Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BlogQuoteSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogQuoteSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *BlogQuote*
 *
 */
type BlogQuoteSliceVariation = BlogQuoteSliceDefault;
/**
 * BlogQuote Shared Slice
 *
 * - **API ID**: `blog_quote`
 * - **Description**: `BlogQuote`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BlogQuoteSlice = prismic.SharedSlice<
  "blog_quote",
  BlogQuoteSliceVariation
>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      BlogDocument,
      BlogCategoryDocumentData,
      BlogCategoryDocument,
      AllDocumentTypes,
      BlogQuoteSliceDefaultPrimary,
      BlogQuoteSliceDefault,
      BlogQuoteSliceVariation,
      BlogQuoteSlice,
    };
  }
}
